spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/barlo921/aira.git
          search-paths: 'services-configs/'
          username:
          password:
          clone-on-start: true
          default-label: main

server:
  port: 8888