server:
  port: 0
  error:
    include-message: always

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}

spring:
  config:
    activate:
      on-profile: ${activatedProperties}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

---

spring:
  config:
    activate:
      on-profile: ${activatedProperties}
  datasource:
    url: jdbc:h2:mem:test
    username: admin
    password: password
    driver-class-name: org.h2.Driver
    data: classpath:db/populateH2.sql