server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'